Use qrcode library instead of the qrencode shell command
liquidinvestigations/core pull request #67
Opened 2019-08-12 16:13 UTC by raduklb

Switched from using the `qrencode` shell command to using the [qrcode](https://pypi.org/project/qrcode/) library.

2019-08-16 11:52 UTC, gabriel-v approved these changes
Do we have any tests running the QR code generation? If not, we should add some in another PR.

2019-08-20 20:13 UTC, mgax requested changes
Unfortunately this doesn't work:

![Screenshot from 2019-08-20 23-06-11](https://user-images.githubusercontent.com/27617/63380646-ab242580-c39f-11e9-9e06-7b589d97377e.png)

The image base64-encoded URL looks like this:

```
  <p><img src="data:image/png;base64,///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A///////////////////////////////////////////////////////////////////////////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP////wAAD///AAAP//8AP///////8AAAAAAAAAAAP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP///////8AP////wA/8AAAAD/wA/8AAA///wAAAAP/AD////8AP///////8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP/AAAP/AAAAA/8AAAAD///AAAP/AAAAAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP//////AAAAAAAAAA/8AAAAD/wAAAAP//8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP/AAAAA/8AP//8AP/AAAAA/8AP/AAAP///////////AD////8AP/AAAAA/8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AP///////8AP/AD/wA/8AP///////8AP/AD////8AP////wA/8AP///////8AP//////A//////8AAAAAAAAAAAP/AD/wA/8AP/AD/wA/8AP/AD/wA/8AP/AD/wA/8AAAAAAAAAAAP//////A//////8AAAAAAAAAAAP/AD/wA/8AP/AD/wA/8AP/AD/wA/8AP/AD/wA/8AAAAAA [...]

2019-09-24 12:05 UTC, mgax requested changes

2019-09-24 12:05 UTC, mgax commented on Dockerfile
>   && apt-get clean && rm -rf /var/lib/apt/lists/* \
Since you're removing the only debian package that was being installed, you should also remove the other `apt-get` commands.

2019-09-24 12:05 UTC, mgax commented on liquidcore/twofactor/devices.py
> +    qr_file.close()
The `qrencode` function was meant to encapsulate the operation "take this url and return a png", even if it was just a one-liner. Now it's more lines so it makes even more sense to encapsulate it. Please bring back the function and move the qrcode logic into it.

2019-09-25 11:13 UTC, mgax approved these changes
:+1: we have a winner

2019-09-25 11:14 UTC, merged